spring:
  cloud:
    config:
      name: ms-eureka
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
server:
  port: 8761
#暴露端点
management:
  endpoints:
    web:
      exposure:
        include: "*"