spring:
  application:
    name: ms-gateway
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: admin
#    password: admin
server:
  port: 80
#暴露端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}